version: "3.9"

services:

  elasticsearch:
    container_name: pp_elasticsearch
    image: elasticsearch:7.12.1
    ports:
      - 9200:9200
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx2g"

networks:
  default:
    driver: bridge
